create table orders (id int8 generated by default as identity, address varchar(255), latitude float8, longitude float8, moment timestamp, status int4, primary key (id));
create table orders_products (order_id int8 not null, product_id int8 not null, primary key (order_id, product_id));
create table products (id int8 generated by default as identity, description varchar(255), image_uri varchar(255), name varchar(255), price float8, primary key (id));
alter table if exists orders_products add constraint FK43vke5jd6eyasd92t3k24kdxq foreign key (product_id) references products;
alter table if exists orders_products add constraint FKe4y1sseio787e4o5hrml7omt5 foreign key (order_id) references orders;
